import { IThemes } from "./models";
import { colors } from "../CSS/colors";

const {
    dark,
    light,
    normal,
    // pitchDark,
    pitchLight,
    ultraDark,
    ultraLight,
    veryDark,
    veryLight,
} = colors;

export const defaultThemes: IThemes = {
    light: {
        name: "light",
        colors: {
            pageBackground: light.white,
            altPageBackground: normal.white,
            defaultText: ultraDark.black,
            textBackground: ultraLight.onyx,
            themeSwitchOn: normal.white,
            themeSwitchOff: normal.onyx,
            defaultColorOverlay: light.white,
            card: pitchLight.white,
            altCard: veryDark.black,
            defaultShadow: normal.black,
            altDefaultShadow: light.white,
            cardShadow: veryDark.white,
            cardSubtitle: light.orange,
            cardFooter: light.black,
            defaultErrorBg: light.red,
            defaultErrorText: veryDark.red,
            altErrorText: dark.red,
            buttonBg: dark.white,
            buttonText: veryLight.white,
            modalBg: veryLight.white,
            modalText: normal.black,
            modalShadow: normal.black,
            sectionBackground: pitchLight.white,
            tooltip: ultraDark.black,
            tooltipText: normal.white,
            toastBackground: normal.white,
            toastProgress: veryLight.onyx,
            tableBorder: veryDark.white,
            tableBackground: veryLight.white,
            tableAltBorder: veryLight.onyx,
            primary: "#1f6fbf",
            secondary: "#656a6e",
            warn: "#e89b15",
            danger: "#c91e1e",
            info: "#1ec99e",
        },
    },
    dark: {
        name: "dark",
        colors: {
            pageBackground: veryDark.onyx,
            altPageBackground: dark.onyx,
            defaultText: pitchLight.white,
            textBackground: normal.onyx,
            themeSwitchOn: normal.white,
            themeSwitchOff: normal.onyx,
            defaultColorOverlay: ultraDark.black,
            card: dark.onyx,
            altCard: veryLight.white,
            defaultShadow: normal.white,
            altDefaultShadow: light.black,
            cardShadow: ultraDark.onyx,
            cardSubtitle: dark.orange,
            cardFooter: dark.white,
            defaultErrorBg: veryDark.red,
            defaultErrorText: veryLight.red,
            altErrorText: light.red,
            buttonBg: normal.onyx,
            buttonText: veryLight.white,
            modalBg: veryDark.black,
            modalText: normal.white,
            modalShadow: veryDark.black,
            sectionBackground: dark.onyx,
            tooltip: veryDark.onyx,
            tooltipText: normal.white,
            toastBackground: dark.onyx,
            toastProgress: veryDark.white,
            tableBorder: light.onyx,
            tableBackground: dark.onyx,
            tableAltBorder: normal.white,
            primary: "#1f6fbf",
            secondary: "#656a6e",
            warn: "#e89b15",
            danger: "#c91e1e",
            info: "#1ec99e",
        },
    },
};
